### ISSUE TITLE
Error on len(feature class list) when None. No handling

### ISSUE THREAD

**Issue by CJuice** [CJuice/DoIT_GISDataInspection_Project#4]
A call to arcpy.ListFeatureClasses on prod feature datasets should return a list of feature classes or an empty list at least. For some reason it is returning None. In print statement, call to len() on None causes failure. Not handled because wasn't expected to happen. Needs handling.

Error Message: Traceback (most recent call last):
  File "D:\Scripts\GIS_OpenDataInspection_ToSocrata\InventoryGISDataInSDEGDB.py", line 465, in <module>
    main()
  File "D:\Scripts\GIS_OpenDataInspection_ToSocrata\InventoryGISDataInSDEGDB.py", line 250, in main
    print("\tFC List (len={length}): {fc_list}".format(length=len(feature_classes_list), fc_list=feature_classes_list))
TypeError: object of type 'NoneType' has no len()

**Comment by CJuice** [comment]
created check for None
